# Generated by Django 4.2.3 on 2023-07-04 15:06

from django.db import migrations, models
import w2m.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_name', models.CharField(default='New Group', max_length=50)),
                ('group_code', models.CharField(default=w2m.models.random_code, max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('belonging_groups', models.ManyToManyField(blank=True, to='w2m.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(to='w2m.user'),
        ),
    ]
