# Generated by Django 4.2.3 on 2023-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2m', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_unavailable_datetimes',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
