# Generated by Django 4.2.3 on 2023-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2m', '0003_alter_group_group_unavailable_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
