# Generated by Django 4.2.3 on 2023-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2m', '0004_alter_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_unavailable_datetimes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
